version: '3'
services:
  producer:
    build: 
      context: .
    command: npm run producer
    environment: 
      REDIS_HOST: redis
  consumer:
    build: 
      context: .
    command: npm run consumer
    environment: 
      REDIS_HOST: redis
  stats:
    build: 
      context: .
    command: npm run stats
    environment: 
      REDIS_HOST: redis
  redis:
    image: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/config.ini:/etc/grafana/config.ini